name: NewTMSv8
version: '8.1.1'
main: me.cyperion.ntms.NewTMSv8
softdepend: [Vault]
api-version: '1.20'
commands:
  admin:
    description: 管理員專用指令，用於開發插件的。
    usage: /admin
  warp:
    description: 可以傳送到 資源界/床重生點/台灣
    usage: /warp <rs/bed/tw>
  enderchest:
    description: 可以隨時隨地開啟終界箱
    usage: /enderchest
  menu:
    description: 打開臺灣地圖的主選單
    usage: /menu
  tpa:
    description: 與上一季一樣有tpa功能，可以透過詢問對方來傳送到對方的位置。接受或拒絕的方法在收到tpa請求時會說明
  tpaccept:
    description: 接受tpa請求
  tpadeny:
    description: 拒絕tpa請求
  ntms:
    description: 介紹台灣的新功能
    usage: /ntms help
  signin:
    description: 每次開啟伺服器時，都可以簽到，獲得不一定的現金。
  pay:
    description: 可以給予其他玩家錢的指令
  class:
    description: 選擇玩家職業的指令
